//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Table.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Priority { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    
        public virtual User User { get; set; }

        public Task(int id, int userid, string desc, DateTime data, string priority, int number, bool iscomplete)
        {
            this.Id = id;
            this.UserId = userid;
            this.Description = desc;
            this.Data = data;
            this.Priority = priority;
            this.Number = number;
            this.IsComplete = iscomplete;
        }
    }
}
